### ISSUE TITLE
Using mutable with monad transformers?

### ISSUE THREAD

**Issue by gilgamec** [mstksg/mutable#1]
It's not clear to me how to use `Mutable` with monad transformers. As a simple example, I'll sometimes put a mutable reference into a Reader to work with it:

```haskell
mvHead :: (PrimMonad m, MonadReader (MVector (PrimState m) Int) m) => m Int
mvHead = ask >>= \mv -> read mv 0

type MyMonad m = ReaderT (MVector (PrimState m) Int) m

runMyMonad :: Vector Int -> (forall m. PrimMonad m => MyMonad m a) -> (a,Vector Int)
runMyMonad v m = runST $ do
  ref <- thaw v
  a <- runReaderT m ref
  v' <- freeze ref
  pure (a,v')
```

This works because `MVector` is tagged with `PrimState m`, which is shared by all transformed versions of the base `PrimMonad`. However, mutable's `Ref`s are tagged with the type of the actual monad itself, so I can't do this:

```haskell
data MyState = MyState { vec :: Vector Int } deriving Generic
instance PrimMonad m => Mutable m MyState where
  Ref m MyState = GRef m MyState

mvHead :: (PrimMonad m, MonadReader (Ref m MyState) m) => m Int
mvHead = do
  ref <- ask
  withField #vec ref $ \mv -> read mv 0

type MyMonad m = ReaderT (Ref ??? MyState) m

runMyMonad :: Vector Int -> (forall m. PrimMonad m => MyMonad m a) -> (a,Vector Int)
runMyMonad v m = runST $ do
  ref <- thawRef (MyState v)
  a <- runReaderT m ref
  MyState v' <- freezeRef ref
  pure (a,v')
```

What type should `MyMonad` be? The reference is thawed in `ST`, so it has to be `Ref (ST s) MyState`, but the monadic operation (like `mvHead`) wants it in whatever the `MonadReader` is. Am I missing something here? Is there a way I'm unaware of to recast the `Ref` through the  transformer stack, or a way to reference the base `PrimMonad`?

**Comment by mstksg** [comment]
This feels a little familiar, and I'll look a little more into it.  However, it vaguely reminds me of something that I've addressed in the past with *[remutable][]*.

However, this does sort of make me wonder why I don't just have the `Ref` be parameterized by the `PrimState` in the first place.  I believe the original intent was to make this usable by things that aren't instances of `PrimMonad`...but I'm not sure if anyone is planning on taking advantage of this.  I have only considered using this for a situation like a GPU EDSL, but it might be possible that if the GPU EDSL can't be made to work with `PrimMonad`, then it might not even be usable with `Mutable` at all.

[remutable]: https://hackage.haskell.org/package/mutable-0.1.0.1/docs/Data-Mutable-Class.html#v:reMutable

**Comment by mstksg** [comment]
The new version *0.2.0.0* should make this much simpler to deal with :)  `Ref` is no longer tied to to the monad it was created in -- just by `s`, or `PrimState m`.  So now the same reference can be used with multiple monads through monad transformers.

Let me know if this helps with your situation or if you have any issues!
